# Generated by Django 4.1.7 on 2023-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C16QS_IMEI_Writter', '0003_hardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(max_length=3)),
                ('socket_id', models.CharField(default='SOCKET', max_length=15)),
                ('comport', models.CharField(default='COM', max_length=6)),
            ],
        ),
    ]
