# Generated by Django 4.2.4 on 2023-10-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C16QS_IMEI_Writter', '0004_socket_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket_mapping',
            name='sn',
            field=models.IntegerField(),
        ),
    ]
