# Generated by Django 4.2.4 on 2023-10-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C16QS_IMEI_Writter', '0005_alter_socket_mapping_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='hw',
            new_name='hardware_version',
        ),
    ]
