# Generated by Django 4.2.4 on 2023-10-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C16QS_IMEI_Writter', '0006_rename_hw_hardware_hardware_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='hardware_version',
            new_name='hw',
        ),
    ]
